env:
  global:
    - CC_TEST_REPORTER_ID=560880ac6c53f1974e13d909ed80bff2e9fb97cc38fd60b2f9c193b73275ff25
language: node_js
node_js:
  - 'stable'
cache:
  directories:
    - node_modules
install:
  - npm install

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - npm test -- -u
after_success:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
