// Alert
export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';

// Auth
export const SIGNUP_START = 'SIGNUP_START';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAIL = 'SIGNUP_FAIL';

export const ACTIVATE_START = 'ACTIVATE_START';
export const ACTIVATE_SUCCESS = 'ACTIVATE_SUCCESS';
export const ACTIVATE_FAIL = 'ACTIVATE_FAIL';

export const LOGIN_START = 'LOGIN_START';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';

export const REQUEST_RESET_LINK_START = 'REQUEST_RESET_LINK_START';
export const REQUEST_RESET_LINK_SUCCESS = 'REQUEST_RESET_LINK_SUCCESS';
export const REQUEST_RESET_LINK_FAIL = 'REQUEST_RESET_LINK_FAIL';

export const RESET_PASSWORD_START = 'RESET_PASSWORD_START';
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS';
export const RESET_PASSWORD_FAIL = 'RESET_PASSWORD_FAIL';

// Profile
export const FETCH_USER_PROFILE_START = 'FETCH_USER_PROFILE_START';
export const FETCH_USER_PROFILE_SUCCESS = 'FETCH_USER_PROFILE_SUCCESS';
export const FETCH_USER_PROFILE_FAIL = 'FETCH_USER_PROFILE_FAIL';

export const UPDATE_USER_PROFILE_START = 'UPDATE_USER_PROFILE_START';
export const UPDATE_USER_PROFILE_SUCCESS = 'UPDATE_USER_PROFILE_SUCCESS';
export const UPDATE_USER_PROFILE_FAIL = 'UPDATE_USER_PROFILE_FAIL';

export const FETCH_USER_ARTICLES_START = 'FETCH_USER_ARTICLES_START';
export const FETCH_USER_ARTICLES_SUCCESS = 'FETCH_USER_ARTICLES_SUCCESS';
export const FETCH_USER_ARTICLES_FAIL = 'FETCH_USER_ARTICLES_FAIL';

export const FETCH_USER_FOLLOWERS_START = 'FETCH_USER_FOLLOWERS_START';
export const FETCH_USER_FOLLOWERS_SUCCESS = 'FETCH_USER_FOLLOWERS_SUCCESS';
export const FETCH_USER_FOLLOWERS_FAIL = 'FETCH_USER_FOLLOWERS_FAIL';

export const FETCH_USER_FOLLOWEES_START = 'FETCH_USER_FOLLOWEES_START';
export const FETCH_USER_FOLLOWEES_SUCCESS = 'FETCH_USER_FOLLOWEES_SUCCESS';
export const FETCH_USER_FOLLOWEES_FAIL = 'FETCH_USER_FOLLOWEES_FAIL';

export const FOLLOW_USER_START = 'FOLLOW_USER_START';
export const FOLLOW_USER_SUCCESS = 'FOLLOW_USER_SUCCESS';
export const FOLLOW_USER_FAIL = 'FOLLOW_USER_FAIL';

export const UNFOLLOW_USER_START = 'UNFOLLOW_USER_START';
export const UNFOLLOW_USER_SUCCESS = 'UNFOLLOW_USER_SUCCESS';
export const UNFOLLOW_USER_FAIL = 'UNFOLLOW_USER_FAIL';

// Articles
export const CREATE_ARTICLE_START = 'CREATE_ARTICLE_START';
export const CREATE_ARTICLE_SUCCESS = 'CREATE_ARTICLE_SUCCESS';
export const CREATE_ARTICLE_FAIL = 'CREATE_ARTICLE_FAIL';

export const FETCH_ARTICLES_START = 'FETCH_ARTICLES_START';
export const FETCH_ARTICLES_SUCCESS = 'FETCH_ARTICLES_SUCCESS';
export const FETCH_ARTICLES_FAIL = 'FETCH_ARTICLES_FAIL';

export const FETCH_ARTICLE_START = 'FETCH_ARTICLE_START';
export const FETCH_ARTICLE_SUCCESS = 'FETCH_ARTICLE_SUCCESS';
export const FETCH_ARTICLE_FAIL = 'FETCH_ARTICLE_FAIL';

export const DELETE_ARTICLE_START = 'DELETE_ARTICLE_START';
export const DELETE_ARTICLE_SUCCESS = 'DELETE_ARTICLE_SUCCESS';
export const DELETE_ARTICLE_FAIL = 'DELETE_ARTICLE_FAIL';

export const UPDATE_ARTICLE_START = 'UPDATE_ARTICLE_START';
export const UPDATE_ARTICLE_SUCCESS = 'UPDATE_ARTICLE_SUCCESS';
export const UPDATE_ARTICLE_FAIL = 'UPDATE_ARTICLE_FAIL';

// Votes
export const LIKE_ARTICLE_START = 'LIKE_ARTICLE_START';
export const LIKE_ARTICLE_SUCCESS = 'LIKE_ARTICLE_SUCCESS';
export const LIKE_ARTICLE_FAIL = 'LIKE_ARTICLE_FAIL';

export const DISLIKE_ARTICLE_START = 'DISLIKE_ARTICLE_START';
export const DISLIKE_ARTICLE_SUCCESS = 'DISLIKE_ARTICLE_SUCCESS';
export const DISLIKE_ARTICLE_FAIL = 'DISLIKE_ARTICLE_FAIL';

// Bookmarks
export const BOOKMARK_ARTICLE_START = 'BOOKMARK_ARTICLE_START';
export const BOOKMARK_ARTICLE_SUCCESS = 'BOOKMARK_ARTICLE_SUCCESS';
export const BOOKMARK_ARTICLE_FAIL = 'BOOKMARK_ARTICLE_FAIL';

export const UNBOOKMARK_ARTICLE_START = 'UNBOOKMARK_ARTICLE_START';
export const UNBOOKMARK_ARTICLE_SUCCESS = 'UNBOOKMARK_ARTICLE_SUCCESS';
export const UNBOOKMARK_ARTICLE_FAIL = 'UNBOOKMARK_ARTICLE_FAIL';

export const FETCH_USER_BOOKMARKS_START = 'FETCH_USER_BOOKMARKS_START';
export const FETCH_USER_BOOKMARKS_SUCCESS = 'FETCH_USER_BOOKMARKS_SUCCESS';
export const FETCH_USER_BOOKMARKS_FAIL = 'FETCH_USER_BOOKMARKS_FAIL';

// Comments
export const COMMENT_ARTICLE_START = 'COMMENT_ARTICLE_START';
export const COMMENT_ARTICLE_SUCCESS = 'COMMENT_ARTICLE_SUCCESS';
export const COMMENT_ARTICLE_FAIL = 'COMMENT_ARTICLE_FAIL';

export const FETCH_ARTICLE_COMMENTS_START = 'FETCH_ARTICLE_COMMENTS_START';
export const FETCH_ARTICLE_COMMENTS_SUCCESS = 'FETCH_ARTICLE_COMMENTS_SUCCESS';
export const FETCH_ARTICLE_COMMENTS_FAIL = 'FETCH_ARTICLE_COMMENTS_FAIL';

// Comments Votes
export const LIKE_COMMENT_START = 'LIKE_COMMENT_START';
export const LIKE_COMMENT_SUCCESS = 'LIKE_COMMENT_SUCCESS';
export const LIKE_COMMENT_FAIL = 'LIKE_COMMENT_FAIL';

export const DISLIKE_COMMENT_START = 'DISLIKE_COMMENT_START';
export const DISLIKE_COMMENT_SUCCESS = 'DISLIKE_COMMENT_SUCCESS';
export const DISLIKE_COMMENT_FAIL = 'DISLIKE_COMMENT_FAIL';

// Ratings
export const FETCH_ARTICLE_RATINGS_START = 'FETCH_ARTICLE_RATINGS_START';
export const FETCH_ARTICLE_RATINGS_SUCCESS = 'FETCH_ARTICLE_RATINGS_SUCCESS';
export const FETCH_ARTICLE_RATINGS_FAIL = 'FETCH_ARTICLE_RATINGS_FAIL';

export const RATE_ARTICLE_START = 'RATE_ARTICLE_START';
export const RATE_ARTICLE_SUCCESS = 'RATE_ARTICLE_SUCCESS';
export const RATE_ARTICLE_FAIL = 'RATE_ARTICLE_FAIL';

// Notifications
export const FETCH_NOTIFICATIONS_START = 'FETCH_NOTIFICATIONS_START';
export const FETCH_NOTIFICATIONS_SUCCESS = 'FETCH_NOTIFICATIONS_SUCCESS';
export const FETCH_NOTIFICATIONS_FAIL = 'FETCH_NOTIFICATIONS_FAIL';

export const READ_NOTIFICATION_START = 'READ_NOTIFICATION_START';
export const READ_NOTIFICATION_SUCCESS = 'READ_NOTIFICATION_SUCCESS';
export const READ_NOTIFICATION_FAIL = 'READ_NOTIFICATION_FAIL';

export const NOTIFICATIONS_SUBSCRIPTION_START =
  'NOTIFICATIONS_SUBSCRIPTION_START';
export const NOTIFICATIONS_SUBSCRIPTION_SUCCESS =
  'NOTIFICATIONS_SUBSCRIPTION_SUCCESS';
export const NOTIFICATIONS_SUBSCRIPTION_FAIL =
  'NOTIFICATIONS_SUBSCRIPTION_FAIL';

// Search
export const SEARCH_START = 'SEARCH_START';
export const SEARCH_SUCCESS = 'SEARCH_SUCCESS';
export const SEARCH_FAIL = 'SEARCH_FAIL';

// Highlights
export const FETCH_HIGHLIGHTS_START = 'FETCH_HIGHLIGHTS_START';
export const FETCH_HIGHLIGHTS_SUCCESS = 'FETCH_HIGHLIGHTS_SUCCESS';
export const FETCH_HIGHLIGHTS_FAIL = 'FETCH_HIGHLIGHTS_FAIL';

export const HIGHLIGHT_TEXT_START = 'HIGHLIGHT_TEXT_START';
export const HIGHLIGHT_TEXT_SUCCESS = 'HIGHLIGHT_TEXT_SUCCESS';
export const HIGHLIGHT_TEXT_FAIL = 'HIGHLIGHT_TEXT_FAIL';
